---
name: "pull-requests"

on:
  push:
    branches:
      - "*"
      - "*/*"
      - "**"
      - "!main"

jobs:
  tagged-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2"

      - name: "lint"
        run: "./bin/lint"
